### ISSUE TITLE
license URL has trailing space

### ISSUE THREAD

**Issue by DavidBiesack** [Redocly/museum-openapi-example#10]
The source openapi.yaml contains
```yaml
  license:
    name: MIT
    url: "https://opensource.org/license/mit/ "
```

with a trailing space. This should be

```yaml
  license:
    name: MIT
    url: "https://opensource.org/license/mit/"
```

(I can submit a PR to fix this)
